import 'models.dart';

/// The source's demo `CHAINS`.
const beuiDefaultSwapChains = [
  BeuiChain(id: 'eth', name: 'Ethereum', symbol: 'Ξ'),
  BeuiChain(
    id: 'sol',
    name: 'Solana',
    symbol: '◎',
    tone: BeuiChainTone.secondary,
  ),
  BeuiChain(id: 'base', name: 'Base', symbol: 'B', tone: BeuiChainTone.accent),
  BeuiChain(
    id: 'arb',
    name: 'Arbitrum',
    symbol: 'A',
    tone: BeuiChainTone.muted,
  ),
  BeuiChain(
    id: 'op',
    name: 'Optimism',
    symbol: 'O',
    tone: BeuiChainTone.destructive,
  ),
  BeuiChain(
    id: 'poly',
    name: 'Polygon',
    symbol: 'P',
    tone: BeuiChainTone.primarySoft,
  ),
  BeuiChain(id: 'bnb', name: 'BNB', symbol: 'B', tone: BeuiChainTone.secondary),
  BeuiChain(
    id: 'avax',
    name: 'Avalanche',
    symbol: 'A',
    tone: BeuiChainTone.destructiveSoft,
  ),
];

/// The source's demo `TOKENS`.
const beuiDefaultSwapTokens = [
  BeuiToken(
    id: 'eth-eth',
    symbol: 'ETH',
    name: 'Ether',
    chainId: 'eth',
    balance: 1.245,
    usd: 3142,
    popular: true,
  ),
  BeuiToken(
    id: 'eth-weth',
    symbol: 'WETH',
    name: 'Wrapped Ether',
    chainId: 'eth',
    balance: 0.5,
    usd: 3142,
    popular: true,
  ),
  BeuiToken(
    id: 'eth-usdc',
    symbol: 'USDC',
    name: 'USD Coin',
    chainId: 'eth',
    balance: 4521,
    usd: 1,
    popular: true,
  ),
  BeuiToken(
    id: 'eth-usdt',
    symbol: 'USDT',
    name: 'Tether',
    chainId: 'eth',
    balance: 2100,
    usd: 1,
    popular: true,
  ),
  BeuiToken(
    id: 'eth-dai',
    symbol: 'DAI',
    name: 'Dai Stablecoin',
    chainId: 'eth',
    balance: 800,
    usd: 1,
    popular: true,
  ),
  BeuiToken(
    id: 'eth-wbtc',
    symbol: 'WBTC',
    name: 'Wrapped Bitcoin',
    chainId: 'eth',
    balance: 0.04,
    usd: 96000,
    popular: true,
  ),
  BeuiToken(
    id: 'eth-link',
    symbol: 'LINK',
    name: 'ChainLink Token',
    chainId: 'eth',
    balance: 120,
    usd: 22,
    address: '0x51...86ca',
    trending: true,
  ),
  BeuiToken(
    id: 'eth-aztec',
    symbol: 'AZTEC',
    name: 'AZTEC',
    chainId: 'eth',
    balance: 0,
    address: '0xa2...62d2',
    trending: true,
  ),
  BeuiToken(
    id: 'eth-cfg',
    symbol: 'CFG',
    name: 'Centrifuge',
    chainId: 'eth',
    balance: 0,
    address: '0xcc...8a94',
    trending: true,
  ),
  BeuiToken(
    id: 'eth-ondo',
    symbol: 'ONDO',
    name: 'Ondo',
    chainId: 'eth',
    balance: 0,
    address: '0xfa...9be3',
    trending: true,
  ),
  BeuiToken(
    id: 'sol-sol',
    symbol: 'SOL',
    name: 'Solana',
    chainId: 'sol',
    balance: 12.4,
    usd: 168,
  ),
  BeuiToken(
    id: 'sol-usdc',
    symbol: 'USDC',
    name: 'USD Coin',
    chainId: 'sol',
    balance: 985.32,
    usd: 1,
  ),
  BeuiToken(
    id: 'base-eth',
    symbol: 'ETH',
    name: 'Ether',
    chainId: 'base',
    balance: 0.65,
    usd: 3142,
  ),
  BeuiToken(
    id: 'base-usdc',
    symbol: 'USDC',
    name: 'USD Coin',
    chainId: 'base',
    balance: 1200,
    usd: 1,
  ),
  BeuiToken(
    id: 'arb-arb',
    symbol: 'ARB',
    name: 'Arbitrum',
    chainId: 'arb',
    balance: 800,
    usd: 0.95,
  ),
  BeuiToken(
    id: 'arb-eth',
    symbol: 'ETH',
    name: 'Ether',
    chainId: 'arb',
    balance: 0.32,
    usd: 3142,
  ),
  BeuiToken(
    id: 'op-op',
    symbol: 'OP',
    name: 'Optimism',
    chainId: 'op',
    balance: 450,
    usd: 2.8,
  ),
  BeuiToken(
    id: 'poly-matic',
    symbol: 'MATIC',
    name: 'Polygon',
    chainId: 'poly',
    balance: 1500,
    usd: 0.75,
  ),
  BeuiToken(
    id: 'bnb-bnb',
    symbol: 'BNB',
    name: 'BNB',
    chainId: 'bnb',
    balance: 0,
    usd: 620,
  ),
  BeuiToken(
    id: 'avax-avax',
    symbol: 'AVAX',
    name: 'Avalanche',
    chainId: 'avax',
    balance: 0,
    usd: 38,
  ),
];
